# Generated by Django 4.2.4 on 2026-04-15 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("valitextapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sentence",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("edited", "Edited"),
                    ("done", "Done"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
